#!/bin/sh

sudo mkdir /home/pi/graphs
sudo chmod +x /home/pi/graphs
sudo apt-get update -y

sudo apt-get update -y
sudo apt-get install vim-runtime -y
sudo apt-get install vim -y

sudo apt-get install python-scipy -y

sudo apt-get install python-matplotlib -y

pip install wifi

sudo apt-get install python-bluez -y

sudo pip install python-wifi

sudo pip install access_points

sudo echo "pcm.!default { type asym playback.pcm { type plug slave.pcm "hw:0" } capture.pcm { type plug slave.pcm "hw:1" } }" > ~/.asoundrc
